In [1]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

# 5.1 pandas 자료 구조 소개

### 5.1.1 Series

In [36]:
obj= Series([4,7,-5,3])
print(obj) # 왼쪽은 색인 오른쪽은 값
print()
print(obj.values) #values 값
print()
print(obj.index)  #index 값
print()
obj2= Series([4,7,-5,3],index=['d','b','a','c'])
print(obj2)
print()
print(obj2.index)

obj2[['a','c']]

0    4
1    7
2   -5
3    3
dtype: int64

[ 4  7 -5  3]

RangeIndex(start=0, stop=4, step=1)

d    4
b    7
a   -5
c    3
dtype: int64

Index(['d', 'b', 'a', 'c'], dtype='object')


a   -5
c    3
dtype: int64

In [65]:
print(obj2[obj2>2])
print()
print(np.exp(obj2)) #numpy 연산을 해도 색인-값은 계속 유지된다

'b' in obj2 #Series 는 고정길이의 정렬된 사전형

sdata = {'ohio':35000,'texas':71000,'oregon':16000,'utha':5000}
obj3=Series(sdata) # Series 순서대로 색인이 들어간다

states = ['california','ohio','oregon','texas']
obj4 = Series(sdata,index=states)

print()
print(obj4) # california 값이 없어 NaN으로 나옴
print()
print(pd.isnull(obj4)) #null 값을 찾아낸다
print()
print(pd.notnull(obj4)) 

obj4.name='population' #이름
obj4.index.name='state'#index 이름
print()
print(obj4)

d    4
b    7
c    3
dtype: int64

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

california     True
ohio          False
oregon        False
texas         False
dtype: bool

california    False
ohio           True
oregon         True
texas          True
dtype: bool

state
california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
Name: population, dtype: float64


### 5.1.2 DataFrame

In [187]:
data={'state':['ohio','ohio','ohio','nevada','nevada'],
     'year':[2000,2001,2002,2001,2002],
     'pop':[1.5,1.7,3.6,2.4,2.9]}
frame=pd.DataFrame(data,columns=['year','state','pop','dedp'],index=np.arange(5)) #columns 위치 변경 가능

print(frame.columns)
print()
print(frame['state'])

print(frame.year)
frame.ix[3] #특정 index의 column값들을 가져온다
frame['dedp']=np.arange(5.)
frame

Index(['year', 'state', 'pop', 'dedp'], dtype='object')

0      ohio
1      ohio
2      ohio
3    nevada
4    nevada
Name: state, dtype: object
0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64


C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  # This is added back by InteractiveShellApp.init_path()


year   state  pop  dedp
0  2000    ohio  1.5   0.0
1  2001    ohio  1.7   1.0
2  2002    ohio  3.6   2.0
3  2001  nevada  2.4   3.0
4  2002  nevada  2.9   4.0

In [133]:
val = Series([-1.2,-1.5,-1.7],index=[2,3,4]) #index값 설정해줘서 DataFrame 값에 들어갈수 있다. 단 없는곳은 NaN으로 표시

frame['dedp']=val2
frame

val2= Series([10,'home',9,'shop'],index=[1,2,3,4])

hmoe=Series([10,10,10,10,10],index=[np.arange(5)])
hmoe=pd.DataFrame(hmoe)
frame['T or F']=frame.state == 'nevada' # 새로운 column 생성방법

pop={'Nevada':{2001:2.4,2002:2.9},
    'ohio':{2000:1.5,2001:1.7,2002:3.6}}

frame2 = pd.DataFrame(pop)
pop2=pd.DataFrame(pop,index=[2001,2002,2003])
pop2.index.name='year'
pop2.columns.name='state'
pop2.values
frame.values

array([[2000, 'ohio', 1.5, nan, False],
       [2001, 'ohio', 1.7, 10, False],
       [2002, 'ohio', 3.6, 'home', False],
       [2001, 'nevada', 2.4, 9, True],
       [2002, 'nevada', 2.9, 'shop', True]], dtype=object)

### 5.1.3 색인 객체

In [151]:
obj = Series(range(3),index=['a','b','c'])

index=obj.index

index[1:]
index=pd.Index(np.arange(3))
obj2=Series([1.5,-2.5,0],index=index)


In [155]:
2002 in frame2.index


True

# 5.2 핵심기능

### 5.2.1 재색인

In [170]:
obj = Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj2=obj.reindex(['a','b','c','e'])
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [197]:
frame =pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','b','c'],columns=['ohio','texas','california'])
frame

frame2=pd.DataFrame(np.arange(50).reshape((5,10)),index=['a','b','c','d','e'],columns=[np.arange(10)])
frame.reindex(['c','d','e','a']) # reindex로 새로운 index 추가가능

states=['texas','uath','california']
frame.reindex(columns=states) # reindex로 새로운 columns 추가가능
frame

ohio  texas  california
a     0      1           2
b     3      4           5
c     6      7           8

In [213]:
frame
#frame.ix[['1','2','4','0'],states]
states=['hi','hello','nice']
frame=frame.reindex(columns=states)

frame=frame.reindex(['a','b','c','d'])
frame.ix[['a','b','c','d'],states]
frame

C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  import sys


hi  hello  nice
a NaN    NaN   NaN
b NaN    NaN   NaN
c NaN    NaN   NaN
d NaN    NaN   NaN

### 5.2.2 하나의 로우 또는 컬럼 삭제하기

In [218]:
obj=Series(np.arange(5.),index=['a','b','c','d','e'])
obj_new=obj.drop(['c'])   # drop 필요없는 index 값 삭제
obj_new

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [225]:
data= pd.DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','newyork'],columns=['one','two','three','four'])
data.drop(['ohio','utah']) 
data.drop('two',axis=1)  #column 제거하기 위해선 axis=1 을 써야함 axis=0 행

one  three  four
ohio        0      2     3
colorado    4      6     7
utah        8     10    11
newyork    12     14    15

### 5.2.3 색인하기,선택하기, 거르기

In [236]:
obj= Series(np.arange(4.),index=['a','b','c','d'])
obj['b']
obj[1:2]
obj[[1,3]]


obj['b':'c'] # 시작과 끝점을 포함한다
obj

b    1.0
c    2.0
dtype: float64

In [263]:
data=DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','newyork'],columns=['one','two','three','four'])
print(data['two'])
print()
print(data[:2]) # 열순으로 잘라온다
data[data['three']>5] # column three가 5초과인 열만 가져온다

data[data['four']>3]
print()
print(data<5) #불리언으로 입력된다

data[data<5]=0
data

ohio         1
colorado     5
utah         9
newyork     13
Name: two, dtype: int32

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7

            one    two  three   four
ohio       True   True   True   True
colorado   True  False  False  False
utah      False  False  False  False
newyork   False  False  False  False


one  two  three  four
ohio        0    0      0     0
colorado    0    5      6     7
utah        8    9     10    11
newyork    12   13     14    15

In [269]:
data.ix['colorado',['two','three']] #필요 행에 필요 열을 가져온다

data.ix['utah',['four','two']]

data.ix[2]

data.ix[data.three>5,:3]

C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/

one  two  three
colorado    0    5      6
utah        8    9     10
newyork    12   13     14

### 5.2.4 산술연산과 데이터 정렬

In [284]:
s1= Series([2.2,3.3,4.4,5.5],index=['a','b','c','d'])
s2= Series([3.3,4.4,5.5,6.6],index=['b','d','e','f'])
print(s1+s2) 

df1= pd.DataFrame(np.arange(9.).reshape((3,3)),index=['ohio','texas','colorado'],columns=list('bcd'))
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),index=['utah','ohio','newyork','seoul'],columns=list('qwb'))
print()
print(df1+df2)
df3=df1+df2
print()
print(df1.add(df2,fill_value=0)) #df1 에다 df2를 추가하고 fill_value 값을 인자로 전달한다 #ass sub div mul


a    NaN
b    6.6
c    NaN
d    9.9
e    NaN
f    NaN
dtype: float64

            b   c   d   q   w
colorado  NaN NaN NaN NaN NaN
newyork   NaN NaN NaN NaN NaN
ohio      5.0 NaN NaN NaN NaN
seoul     NaN NaN NaN NaN NaN
texas     NaN NaN NaN NaN NaN
utah      NaN NaN NaN NaN NaN

             b    c    d    q     w
colorado   6.0  7.0  8.0  NaN   NaN
newyork    8.0  NaN  NaN  6.0   7.0
ohio       5.0  1.0  2.0  3.0   4.0
seoul     11.0  NaN  NaN  9.0  10.0
texas      3.0  4.0  5.0  NaN   NaN
utah       2.0  NaN  NaN  0.0   1.0


b    c    d
ohio      0.0  1.0  2.0
texas     3.0  4.0  5.0
colorado  6.0  7.0  8.0

In [313]:
arr= np.arange(12.).reshape((3,4))
print(arr-arr[0])

frame=DataFrame(np.arange(12.).reshape((3,4)),columns=list('bdef'),index=['ohio','texas','colorado'])
print(frame)
series=frame.ix[0] # 첫번째 열 값들을 가져옴
print()
print(series)

frame-series

series2=Series(range(3),index=['a','b','c'])
frame+series2
series3=frame['d']
frame.sub(series3,axis=0)  #axis 값은 연산을 적용할 축 번호

[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]
            b    d     e     f
ohio      0.0  1.0   2.0   3.0
texas     4.0  5.0   6.0   7.0
colorado  8.0  9.0  10.0  11.0

b    0.0
d    1.0
e    2.0
f    3.0
Name: ohio, dtype: float64


C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


b    d    e    f
ohio     -1.0  0.0  1.0  2.0
texas    -1.0  0.0  1.0  2.0
colorado -1.0  0.0  1.0  2.0

### 5.2.5 함수 적용과 매핑

In [4]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['ohio','colorado','utah','seoul'])
np.abs(frame) #절댓값 함수

f = lambda x:x.max()-x.min()
print(frame)
print(frame.apply(f))
print(frame.apply(f,axis=1))

                 b         d         e
ohio     -0.430631  0.540119 -1.117216
colorado -0.845881 -2.617574  0.942816
utah      2.706062 -2.332759 -0.758767
seoul    -1.464730 -0.192306  0.356132
b    4.170793
d    3.157693
e    2.060032
dtype: float64
ohio        1.657335
colorado    3.560390
utah        5.038821
seoul       1.820862
dtype: float64


In [13]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

format = lambda x: '%.2f'% x
frame.applymap(format)

b      d      e
ohio      -0.43   0.54  -1.12
colorado  -0.85  -2.62   0.94
utah       2.71  -2.33  -0.76
seoul     -1.46  -0.19   0.36

In [14]:
frame['e'].map(format)

ohio        -1.12
colorado     0.94
utah        -0.76
seoul        0.36
Name: e, dtype: object

In [ ]:
### 5.2.6 정렬과 순위

In [29]:
obj=Series(np.arange(4),index=['d','b','a','c'])
print(obj.sort_index()) #index 알파벳 순으로 정렬한다
frame=pd.DataFrame(np.arange(8).reshape((4,2)),index=['b','c','a','d'],columns=['one','two'])
frame.T.sort_index(axis=1) # ()를 꼭 붙여주기!

a    2
b    1
c    3
d    0
dtype: int32


a  b  c  d
one  4  0  2  6
two  5  1  3  7

In [55]:
print(frame.T.sort_index(axis=1,ascending=False))
print()
obj=Series([4,2,6,-12])
print(obj.sort_values())

obj2=Series([4,5,np.nan,5,1])
print(obj2.sort_values()) #NaN 값은 맨 뒤에 위치한다

frame=pd.DataFrame({'b':[2,6,1,2],'c':[1,6,7,2]})
print(frame.sort_values(by='b')) #'b' 열에 맞춰서 정렬해준다
print()
print(frame)
print()
print(frame.sort_values(by=['b','c'])) #첫 번째 'b'열에 맞춰 정렬뒤 'c'맞춰 다음 정렬에 맞춤

   3  2  1  0
b  2  1  6  2
c  2  7  6  1

3   -12
1     2
0     4
2     6
dtype: int64
4    1.0
0    4.0
1    5.0
3    5.0
2    NaN
dtype: float64
   b  c
2  1  7
0  2  1
3  2  2
1  6  6

   b  c
0  2  1
1  6  6
2  1  7
3  2  2

   b  c
2  1  7
0  2  1
3  2  2
1  6  6


In [59]:
obj=Series([6,12,8,1,2,-2,3,4])
obj.rank()

0    6.0
1    8.0
2    7.0
3    2.0
4    3.0
5    1.0
6    4.0
7    5.0
dtype: float64

In [63]:
obj.rank(method='max',ascending=False)


0    3.0
1    1.0
2    2.0
3    7.0
4    6.0
5    8.0
6    5.0
7    4.0
dtype: float64

In [69]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 5.2.7 중복 색인

In [82]:
obj = Series(range(5),index=['a','a','b','c','d'])
print(obj.index.is_unique) #index 값이 중복인지 아닌지
df=pd.DataFrame(np.random.randn(4,3),index=['a','b','c','a'])
df.ix['b',2] #ix 특정 row col 값을 가져올 수 있다

False


C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


0.7115194450614982

### 5.3 기술통계 계산과 요약

In [90]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])
df.sum() #col들을 합
df.sum(axis=1) #row순으로 합
df.mean(axis=1,skipna=False) #nan 값을 제외시킬지 말지

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [100]:
df.idxmax() # 최대값을 가지고 있는 index값을 반환한다
df.idxmin() # '' 최소값
df.cumsum() # 누적합을 구함
df.describe() #한번에 여러통계결과를 만들어낸다

obj=Series(['a','a','b','c']*4)
obj.describe()


count     16
unique     3
top        a
freq       8
dtype: object

### 5.3.1 상관관계와 공분산

In [106]:
import pandas as pd
from pandas_datareader import data

all_data={}
for ticker in ['AAPL','IBM','MSFT','GOOG']:
    all_data[ticker]=data.DataReader(ticker,'yahoo','2015-01-01','2016-01-01')
    
price=pd.DataFrame({tic:data['Adj Close'] for tic,data in all_data.items()})
volume=pd.DataFrame({tic:data['Volume'] for tic,data in all_data.items()})

In [109]:
returns = price.pct_change() # 각 주식의 퍼센트 변화율
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2015-12-24 -0.005340 -0.002093 -0.002687 -0.002546
2015-12-28 -0.011201 -0.004629  0.005030  0.018854
2015-12-29  0.017974  0.015769  0.010724  0.018478
2015-12-30 -0.013059 -0.003148 -0.004244 -0.007211
2015-12-31 -0.019195 -0.012344 -0.014740 -0.015720

In [113]:
returns.MSFT.corr(returns.IBM) #두 Series에 대해 상관관계 분석
returns.MSFT.cov(returns.IBM) #공분산 계산


0.00013044502576386592

In [114]:
returns.corr() #DataFrame에서는 행렬상에서 상관관계,공분산 계산

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.513896  0.522402  0.381052
IBM   0.513896  1.000000  0.549596  0.451361
MSFT  0.522402  0.549596  1.000000  0.520430
GOOG  0.381052  0.451361  0.520430  1.000000

In [115]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000284  0.000116  0.000156  0.000119
IBM   0.000116  0.000178  0.000130  0.000112
MSFT  0.000156  0.000130  0.000316  0.000172
GOOG  0.000119  0.000112  0.000172  0.000345

In [119]:
returns.corrwith(returns.IBM)  #다른 Series나 DataFrame 의 상관관계를 계산해 준다

AAPL    0.513896
IBM     1.000000
MSFT    0.549596
GOOG    0.451361
dtype: float64

In [120]:
returns.corrwith(volume)

AAPL   -0.119688
IBM    -0.297121
MSFT   -0.004252
GOOG    0.405849
dtype: float64

### 5.3.2 유일 값, 값 세기, 멤버쉽

In [128]:
obj=Series(['a','a','b','b','a','c','d'])
print(obj.unique())#중복되는 값을 제외
print()
print(obj.value_counts()) #중복되는 수를 셈
pd.value_counts(obj.values,sort=False) #value_counts
mask = obj.isin(['a','c'])
print(mask) #isin 값이 Series 안에 있는지 없는지 불리안으로 알수있음

['a' 'b' 'c' 'd']

a    3
b    2
d    1
c    1
dtype: int64
0     True
1     True
2    False
3    False
4     True
5     True
6    False
dtype: bool


In [146]:
data= pd.DataFrame({'Qu1':[1,3,4,3,4],'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})
data.apply(pd.value_counts).fillna(0)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

### 5.4 누락된 데이터 처리하기

In [152]:
import numpy as np
string_data=Series(['aardvark','artichoke',np.nan,'avocado'])
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [156]:
string_data[0]=None
string_data.isnull() #None 값도 Na와 같이 취급된다

0     True
1    False
2     True
3    False
dtype: bool

In [158]:
string_data.dropna() #dropna Na 값 제거한다

1    artichoke
3      avocado
dtype: object

### 5.4.1 누락된 데이터 골라내기

In [164]:
from numpy import nan as Na
data=Series([1,Na,5,Na,3])
print(data.dropna())
print()
print(data[data.notnull()]) #Na값이 아닌것들만 가져옴

0    1.0
2    5.0
4    3.0
dtype: float64

0    1.0
2    5.0
4    3.0
dtype: float64


In [173]:
data=pd.DataFrame([[1.,6.5,3.],[1.,Na,Na],[Na,Na,Na],[Na,6.5,3.]])
data.dropna(how='all') #Na값이 전부인 것의 행을 제거
data.dropna(how='any') #Na값을 하나라도 가지고 있는 행을 제거
data.dropna(axis=1,how='any') #axis로 행을 제거할지 열을 제거할지 결정

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [188]:
df=DataFrame(np.random.randn(7,3))
df.ix[:4,1]=Na;df.ix[:2,2]=Na
df.dropna(thresh=3) #thresh 몇개 이상이 있는 열만 표시 

C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


0         1         2
5  2.139506  2.006143 -0.504653
6  0.465113 -1.008960 -1.188399

### 5.4.2 누락된 값 채우기

In [191]:
df.fillna(0) #누락된 값 채우기

0         1         2
0 -0.563883  0.000000  0.000000
1  0.331495  0.000000  0.000000
2 -0.481895  0.000000  0.000000
3 -0.509254  0.000000 -0.670357
4  1.127065  0.000000 -0.003340
5  2.139506  2.006143 -0.504653
6  0.465113 -1.008960 -1.188399

In [192]:
df.fillna({1:0,2:0.1}) #열에 따라 다르게 설정가능

0         1         2
0 -0.563883  0.000000  0.100000
1  0.331495  0.000000  0.100000
2 -0.481895  0.000000  0.100000
3 -0.509254  0.000000 -0.670357
4  1.127065  0.000000 -0.003340
5  2.139506  2.006143 -0.504653
6  0.465113 -1.008960 -1.188399

In [198]:
df=DataFrame(np.random.rand(6,3))
df.ix[2:,1]=Na;df.ix[4:,2]=Na
df.fillna(method='ffill',limit=2) #ffill 

C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  


0         1         2
0  0.696364  0.446366  0.737103
1  0.204089  0.078070  0.020267
2  0.956545  0.078070  0.034794
3  0.618291  0.078070  0.496858
4  0.301853       NaN  0.496858
5  0.160335       NaN  0.496858

In [219]:
data=Series([1,Na,3,Na,5,Na,7])
data.fillna(data.max()) #NA 값을 평균값으로 바꿔서

0    1.0
1    7.0
2    3.0
3    7.0
4    5.0
5    7.0
6    7.0
dtype: float64

### 5.5 계층적색인

In [230]:
data=Series(np.random.randn(10),index=[['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
print(data)
print()
print(data.index)
print()
print(data.b)
print()
print(data['b':'c'])
print(data.ix['b'])

a  1    0.752245
   2   -0.353248
   3    1.092603
b  1   -0.886707
   2    0.316956
   3   -0.286878
c  1   -0.747723
   2    1.750219
d  2   -0.222128
   3   -0.316843
dtype: float64

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

1   -0.886707
2    0.316956
3   -0.286878
dtype: float64

b  1   -0.886707
   2    0.316956
   3   -0.286878
c  1   -0.747723
   2    1.750219
dtype: float64
1   -0.886707
2    0.316956
3   -0.286878
dtype: float64


C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


In [233]:
data[:,2] #하위층 객체 선택가능

a   -0.353248
b    0.316956
c    1.750219
d   -0.222128
dtype: float64

In [239]:
data
data.unstack() # unstack 행,열 값을 index값으로
data.unstack()

1         2         3
a  0.752245 -0.353248  1.092603
b -0.886707  0.316956 -0.286878
c -0.747723  1.750219       NaN
d       NaN -0.222128 -0.316843

In [252]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),index=[['a','a','b','b'],[1,2,1,2]],
                     columns=[['ohio','ohio','colorado'],['green','red','green']])
frame.index.names=['key1','key2']
frame.columns.names=['state','color']
frame['ohio']

color      green  red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### 5.5.1 계층순서 바꾸고 정렬하기

In [260]:
frame.swaplevel('key1','key2') #index 서로 변경해주기
frame.swaplevel(0,1)

state      ohio     colorado
color     green red    green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

### 5.5.2 단계별 요약통계

In [279]:
frame.sum(level='key2')
frame.sum(level='color',axis=1)

color      green  red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [284]:
frame=pd.DataFrame({'a':range(7),'b':range(7,0,-1),'c':['one','one','one','two','two','two','two'],
                   'd':[0,1,2,0,1,2,3]})
frame.set_index(['c','d']) #하나 이상의 열을 index로 설정해 새로운 DataFrame 생성
frame.set_index(['a','b'])
frame.reset_index()

index  a  b    c  d
0      0  0  7  one  0
1      1  1  6  one  1
2      2  2  5  one  2
3      3  3  4  two  0
4      4  4  3  two  1
5      5  5  2  two  2
6      6  6  1  two  3

### 5.6 pandas와 관련된 기타 주제

### 5.6.1 정수 색인

In [289]:
ser=Series(np.arange(3.),index=['a','b','c'])
ser 

a    0.0
b    1.0
c    2.0
dtype: float64

In [296]:
ser3=Series(np.arange(3),index=[-5,1,3])
ser3.iloc[2] #index 종류에 상관없이 그 위치에 값을 표시

2

In [298]:
from pandas_datareader import data as web
pdata=pd.Panel(dict((stk,web.get_data_yahoo(stk)) for stk in ['AAPL','GOOG','MSFT','DELL']))

C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  


TypeError: Panel() takes no arguments

In [299]:
#pdata=pd.Panel(dict((stk,web.get_data_yahoo(stk)) for stk in ['AAPL','GOOG','MSFT','DELL']))

C:\Users\Heewon Moon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  """Entry point for launching an IPython kernel.


TypeError: Panel() takes no arguments