### 3장 IPython 소개

In [ ]:
import numpy as np

a= np.random.randn(100,100)
a

%reset?
%outomagic

In [ ]:
2**27


### 4장 Numpy

In [6]:
#4.1
import numpy as np

data=np.random.randn(2,3)
data*10

data.shape #shape 차원의 크기를 알려줌
data.dtype #dtype 저장된 자료형

dtype('float64')

In [25]:
#4.1.1
data1 = [6,7.5,8,0,1]
arr1=np.array(data1)
arr1

data2 = [[1,2,3,4],[4,5,6,7]]
arr2 = np.array(data2)
arr2

arr2.ndim
arr2.dtype

np.zeros(2) #zeros 0의 배열(갯수)생성
np.zeros((3,2))

np.empty((2,3,2))

np.arange(10) # 숫자 나열 0,1,2,3,4,5,6,7,8,9

#asarray 입력 데이터를 ndarray로 변환
#arange 내장 range함수와 유사 but list 대신 ndarray 반환


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#4.1.2

arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)

print(arr1,arr2) #소수 정수에 따라 뒤에 소수점이 붙냐 안붙냐 차이가 생김

arr=np.array([1,2,3,4,5])
print(arr.dtype)

float_arr=arr.astype(np.float64)   #astype 타입 변경
print(float_arr.dtype)

arr= np.random.randn(1,7)
arr2=arr.astype(np.int32)
print(arr)
print(arr2) #타입변경 소숫점아래는 버려짐

numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)
numeric_strings.astype(float)

int_array=np.arange(10)
calibers=np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)
int_array.astype(calibers.dtype)

empty_unit32=np.empty(8,dtype='u4') #u4 = unit32
empty_unit32

[1. 2. 3.] [1 2 3]
int32
float64
[[-0.16422249  1.30608848 -0.06372749 -0.95726788  0.40794158  0.23676731
  -1.31258756]]
[[ 0  1  0  0  0  0 -1]]


array([1, 2, 3, 4, 4, 5, 6, 7], dtype=uint32)

In [56]:
#4.1.3

#배열은 for 반목문을 작성하지 않고 데이터를 일괄처리할 수 있기 때문에 중요

arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr*arr
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [91]:
#4.1.4

arr=np.arange(10)
print(arr[5])
print(arr[2:4])
arr[3:5]=10
print(arr) #리스와의 차이점 배열조각은 원본배열의 뷰라는 점/데이터 복사 x 뷰에 대한 변경은 그대로 반영

arr_slice=arr[5:8]
arr_slice[1]=1234
print(arr)

arr_slice[:]=64
print(arr) #만약 데이터 복사를 원한다면 arr[5:8].copy() 사용

arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2]) #스칼라값을 부르는게 아니라 1차원을 부름

print(arr2d[0][0])
print(arr2d[0][2])
print(arr2d[2][1])
print(arr2d[2][2]) #콤마로 구분된 색인 리스트를 넘긴다

arr3d =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d[0]) # 2*3 크기의 배열
old_values =arr3d[0].copy()

arr3d[0]=42

print(arr3d)

arr3d[0]=old_values
arr3d

5
[2 3]
[ 0  1  2 10 10  5  6  7  8  9]
[   0    1    2   10   10    5 1234    7    8    9]
[ 0  1  2 10 10 64 64 64  8  9]
[7 8 9]
1
3
8
9
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [101]:
arr3d[1,0]

arr[1:6]
print(arr2d[0:2])
print(arr2d[0:1,0:2])

[[1 2 3]
 [4 5 6]]
[[1 2]]


In [145]:
#4.1.5 불리언 색인

names = np.array(['bob','joe','will','bob','will','joe','joe'])
data=np.random.randn(7,4)

names=='bob'
names.dtype

print(data[names=='bob',2:]) # data 안에  3열 이상의 'bob' row만 불러온다
print(data[names=='bob',3])

print(data[(names!='bob')])

mask = (names=='bob') & (names=='will')

mask  #and or 은 불리언 배열에서 사용 안됨 

[[-0.20347417  1.97264602]
 [ 0.38236472  0.7935688 ]]
[1.97264602 0.7935688 ]
[[ 0.65612788 -0.01218079  0.36307582  0.42909917]
 [-0.47915562  0.33501452 -0.87555643  0.86422772]
 [ 0.66469238  0.51097021  0.09494639 -1.04797177]
 [ 0.91054267  0.53597308 -0.25843099 -0.63496759]
 [-0.96611577 -1.60807733  1.10329996 -0.11856133]]


array([False, False, False, False, False, False, False])

In [149]:
data[data<0]=0
data[names !='joe']

array([[1.18309878, 0.56391442, 0.        , 1.97264602],
       [0.        , 0.33501452, 0.        , 0.86422772],
       [0.31000359, 0.        , 0.38236472, 0.7935688 ],
       [0.66469238, 0.51097021, 0.09494639, 0.        ]])

In [165]:
#4.1.6 팬시 색인

arr=np.empty((8,4))

for i in range(8):
    arr[i]=i
print(arr)
print(arr[[4,3,0,6]])

arr=np.arange(32).reshape((8,4))
print(arr[[1,5,7,2],[0,3,1,2]])#필요한 행에서 0,3,1,2 번쨰 열의 값을 가져온다 첫 list는 안의 전체list 배열 두번째 list는 그 안의 배열

print(arr[np.ix_([1,5,7,2],[0,3,1,2])]) #np_ix 배열 순서를 바꿔준다

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[ 4 23 29 10]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [175]:
#4.1.7 배열 전치와 축 바꾸기

arr=np.arange(15).reshape((3,5))
arr.T

arr=np.arange(100).reshape((2,2,25))


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
         91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [ ]:
#4.2 유니버설 함수

arr= np.ar